### PR TITLE
Add suport for creating addition Istanbul reports

### PR DESCRIPTION
**Pull request by jonnyreeves**
Istanbul provides support for the following coverage reports in various formats including lcov, cobertura and clover as well as an HTML report; this commit gives users the ability to enable said reports and specify where they should be written to in the same fashion as `grunt-qunit-istanbul`.

Note that this changes the current behavior of the library by renaming `options.coverage.coverageFile` to `options.coverage.jsonReport` to be consistent with the other reporters that have been added; by default this file is no longer written and users must opt-in - as a result I would suggest a major/minor version bump if you are happy to merge this PR.

### CODE REVIEW

**Comment by jonnyreeves** [comment]
:+1: Thanks for creating this library; just what I needed, small change to make it integrate with my CI requirements.

**Comment by jonnyreeves** [comment]
any thoughts? It would be great to get this available on NPM please.

**Comment by scotthogan** [comment]
Sorry for not getting to this sooner. It looks good and I will gladly merge in your changes.

However, I did run into a small issue when I was trying to run the tests, the example/js_instrumented files have paths specific to your system in them, which causes the tests to fail. I used istanbul to instrument the files myself from example/js and overwrote the ones you have committed in example/js_instrumented, and then everything worked as expected. Perhaps it is best if we add an instrument step before running the tests, and generate these files rather than checking them in.

**Comment by jonnyreeves** [comment]
Hey @scotthogan, thanks for getting back to me.

> I did run into a small issue when I was trying to run the tests

Whoops! Sorry about that oversight!  I've just pushed a new commit with replaces the absolute paths in the instrumented output with relative paths; I've confirmed this builds OK on another machine so we should be in business. :ballot_box_with_check:

**Pull request merged**
